images:
  ipboard:
    repository: registry.cmer.fr/le-monde-des-reptiles/docker-app/nginx-php7
    tag: latest

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  containerPort: "80"
  ipboard:
    baseUrl: ''
    hostname: ''

service:
  ipboard:
    type: clusterIP
    externalTrafficPolicy: Cluster
    clusterIP:
      http: '80'

ingress:
  ipboard:
    certificate: ''
    enabled: true
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 5Gi
  storageClass: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
