# This file is a template, and might need editing before it works on your project.
build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  tags:
    - synology
    - docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
  script:
    - docker build --pull -t "$DOCKER_REGISTRY_USER/ipboard:latest" .
    - docker push "$DOCKER_REGISTRY_USER/ipboard:latest"
  only:
    - master